name: Build and Test Safari History Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js for root directory
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install root dependencies
      run: npm install
    
    - name: Run sync tests
      run: npm run test:sync
      
    - name: Upload sync test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: sync-test-logs
        path: |
          test/temp-instance-*/*.log
          test/temp-instance-*/LOG*
    
    - name: Set up Node.js for Xcode project
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'SafariHistorySync/package-lock.json'
    
    - name: Install Xcode project dependencies
      run: |
        cd SafariHistorySync
        npm install
    
    - name: Build extension
      run: |
        cd SafariHistorySync
        npm run build
    
    - name: Run extension tests
      run: |
        cd SafariHistorySync
        npm test || echo "No tests to run"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-bundles
        path: |
          SafariHistorySync/dist/*.bundle.js