name: Safari History Sync Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Run sync tests
      run: node test/sync-test.js
      
    # In a real implementation, we would also have tests for the Safari extension
    # using tools like Playwright or Puppeteer to simulate browser interactions